name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trigger PythonAnywhere gitpull webhook
        run: |
          echo "Triggering gitpull webhook on PythonAnywhere..."
          curl -s -X POST https://mikedorin.pythonanywhere.com/gitpull \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$(echo -n '{}' | openssl dgst -sha256 -hmac "${{ secrets.GITHUB_WEBHOOK_SECRET }}" | cut -d' ' -f2)" \
            -d '{}' || true

      - name: Wait a few seconds for git pull to finish
        run: sleep 30

      - name: Reload PythonAnywhere web app
        run: |
          echo "Reloading PythonAnywhere web app..."
          curl -s -X POST https://www.pythonanywhere.com/api/v0/user/mikedorin/webapps/mikedorin.pythonanywhere.com/reload/ \
            -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}"
